name: Push image to GAR

on: workflow_dispatch

env: 
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGISTRY_REGION: us-central1
  GCP_REGISTRY_NAME: oaviles
  IMAGE_NAME: ratings-api

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: us-centra1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
                   
      - name: Build and push to GAR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.GCP_REGISTRY_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.GCP_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest  
          #tags:  ${{ env.GCP_REGISTRY_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.GCP_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}  
          
