# This is a basic workflow to help you get started with Actions

name: Push image to GitHub Registry

on: workflow_dispatch

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Push Image to GitHub Registry
        #working-directory: /src
        run: |
          docker build . -t ghcr.io/OWNER/api:latest
          docker push ghcr.io/OWNER/api:latest

