# This is a basic workflow to help you get started with Actions

name: Push image to GitHub Packages

on: workflow_dispatch

env:
  GIHUB_REGISTRY: ghcr.io
  PACKAGE_NAME: oaviles
  IMAGE_NAME: api
  #TAG: ${{ github.sha }}
  TAG: latest

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GIHUB_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
           
      - name: Build and Push Image to GitHub Registry
        uses: docker/build-push-action@v2
        #working-directory: /src
        with:
          #context: .
          #file: ./Dockerfile
          #platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.GIHUB_REGISTRY }}/${{ env.PACKAGE_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          

